<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>links</string>
	</array>
	<key>name</key>
	<string>Links</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.links</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(^\")*</string>
					<key>name</key>
					<string>string.unquoted.links</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.links</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((\s+|[\(\|\.\?!~:,]))([A-Z][A-Za-z0-9_]+)</string>
			<key>name</key>
			<string>storage.type.links</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(sig|fun)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.links</string>
				</dict>
			</dict>
			<key>end</key>
			<string>:|\(|\s+</string>
			<key>name</key>
			<string>stuff.links</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([a-z][A-Za-z0-9_]+)</string>
					<key>name</key>
					<string>entity.name.function.links</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>need to deal with cases where</string>
			<key>match</key>
			<string>\#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.links</string>
		</dict>
		<dict>
			<key>match</key>
			<string>typename|var|(lin)?fun|sig|case|switch</string>
			<key>name</key>
			<string>keyword.control.links</string>
		</dict>
		<dict>
			<key>match</key>
			<string>spawn|spawnAngel|spawnDemon|offer|receive|send|select|(lin)?(fork|knife)|ignore</string>
			<key>name</key>
			<string>keyword.control.sessions.links</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\-?[0-9]+(\.[0-9]+)?)</string>
			<key>name</key>
			<string>constant.numeric.links</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\-&gt;|~&gt;?|:|\?|!|\[&amp;|&amp;\]</string>
			<key>name</key>
			<string>keyword.operator.types.links</string>
		</dict>
		<dict>
			<key>match</key>
			<string>::|=|\|</string>
			<key>name</key>
			<string>keyword.operator.other.links</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\+|\-|\*|/|\^)\.?|mod</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.links</string>
		</dict>
		<dict>
			<key>match</key>
			<string>_|true|false</string>
			<key>name</key>
			<string>constant.language.links</string>
		</dict>
		<dict>
			<key>match</key>
			<string>testcolor</string>
			<key>name</key>
			<string>constant.language.links</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.links</string>
	<key>uuid</key>
	<string>8f604b2a-6eae-462c-94b1-bd725f391351</string>
</dict>
</plist>
